"""create users sessions transcripts tables

Revision ID: fe8c0ebdf203
Revises: 2f86dbb9543d
Create Date: 2026-07-10 04:11:51.416469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8c0ebdf203'
down_revision: Union[str, Sequence[str], None] = '2f86dbb9543d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
